In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
path = "C:\\Users\\91897\\Downloads\\teleCust1000t.csv"
df = pd.read_csv(path)
df.head()

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9    64.0   4       5     0.0       0   
1       3      11   33        1        7   136.0   5       5     0.0       0   
2       3      68   52        1       24   116.0   1      29     0.0       1   
3       2      33   33        0       12    33.0   2       0     0.0       1   
4       2      23   30        1        9    30.0   1       2     0.0       0   

   reside  custcat  
0       2        1  
1       6        4  
2       2        3  
3       1        1  
4       4        3

In [10]:
df['custcat'].value_counts()

custcat
3    281
1    266
4    236
2    217
Name: count, dtype: int64

In [19]:
df.columns

Index(['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat'],
      dtype='object')

In [20]:
x = df[['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside']].values
x[0:5]

array([[  2.,  13.,  44.,   1.,   9.,  64.,   4.,   5.,   0.,   0.,   2.],
       [  3.,  11.,  33.,   1.,   7., 136.,   5.,   5.,   0.,   0.,   6.],
       [  3.,  68.,  52.,   1.,  24., 116.,   1.,  29.,   0.,   1.,   2.],
       [  2.,  33.,  33.,   0.,  12.,  33.,   2.,   0.,   0.,   1.,   1.],
       [  2.,  23.,  30.,   1.,   9.,  30.,   1.,   2.,   0.,   0.,   4.]])

In [23]:
y = df['custcat'].values
y[0:5]

array([1, 4, 3, 1, 3], dtype=int64)

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=4)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800, 11), (200, 11), (800,), (200,))

In [25]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_norm = scaler.fit(X_train).transform(X_train.astype(float))
X_train_norm[0:5]

array([[-1.28618818e+00, -1.53085556e+00, -8.49354628e-01,
         1.00752834e+00, -7.46393214e-01, -4.83608776e-01,
         1.12305195e+00, -7.02283455e-01, -2.23313158e-01,
        -1.01005050e+00,  1.83304333e+00],
       [-4.79805457e-02,  2.51253999e-01,  3.44957012e-01,
         1.00752834e+00,  2.45326718e-01, -2.71543263e-01,
        -5.40728715e-01, -1.25385370e-04, -2.23313158e-01,
        -1.01005050e+00,  1.83304333e+00],
       [-1.28618818e+00, -7.80493639e-01, -6.90113076e-01,
         1.00752834e+00, -5.21892614e-02, -4.92444839e-01,
        -1.37261905e+00, -8.02591750e-01, -2.23313158e-01,
        -1.01005050e+00,  1.83304333e+00],
       [-4.79805457e-02, -1.53085556e+00, -3.71629972e-01,
        -9.92527915e-01,  1.46154725e-01, -4.74772713e-01,
        -1.37261905e+00, -8.02591750e-01, -2.23313158e-01,
         9.90049504e-01, -9.33814526e-01],
       [ 1.19022709e+00, -2.17722200e-01, -6.10492300e-01,
        -9.92527915e-01, -2.50533248e-01,  2.40948394e-01,
  

In [27]:
# classification

from sklearn.neighbors import KNeighborsClassifier
# training
knn = KNeighborsClassifier(n_neighbors= 4)
knn.fit(X_train_norm,y_train)
knn

KNeighborsClassifier(n_neighbors=4)

In [32]:
X_test_norm = scaler.fit(X_test).transform(X_test.astype(float))

# predicting

yhat = knn.predict(X_test_norm)
yhat[0:5]

array([3, 1, 3, 2, 4], dtype=int64)

In [33]:
y_test[0:5]

array([4, 1, 1, 2, 4], dtype=int64)

In [35]:
# accuracy evaluation

from sklearn import metrics

print("Train set accuracy: ", metrics.accuracy_score(y_train, knn.predict(X_train_norm)))
print("Test set accuracy: ", metrics.accuracy_score(y_test, yhat))


Train set accuracy:  0.5475
Test set accuracy:  0.33


## Practice

In [36]:
knn1 = KNeighborsClassifier(n_neighbors=6)
knn1.fit(X_train_norm,y_train)
knn1

KNeighborsClassifier(n_neighbors=6)

In [37]:
yhat1 = knn1.predict(X_test_norm)
yhat1[0:10]

array([3, 3, 3, 2, 4, 4, 4, 4, 2, 1], dtype=int64)

In [38]:
y_test[0:10]

array([4, 1, 1, 2, 4, 4, 3, 1, 3, 4], dtype=int64)

In [39]:
metrics.accuracy_score(y_test,yhat1)

0.335